### ISSUE TITLE
Running program without argument throws error, should show help

### ISSUE THREAD

**Issue by sandeeprenjith** [sandeeprenjith/dnsblast#3]
╭─nd33p@trv-wl-srenjith ~/go/src/github.com/sandeeprenjith/dnsblast ‹master*›
╰─$ dnsblast
2019/11/14 15:00:44  === Error Handler ===
2019/11/14 15:00:44 read udp 127.0.0.1:61821->127.0.0.1:53: i/o timeout
2019/11/14 15:00:44  === Error Handler ===
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x62afbe]

goroutine 1 [running]:
github.com/sandeeprenjith/dnsblast/qry.SimpleQuery(0x6a7c78, 0x9, 0x6a6cd4, 0x2, 0xc000018340, 0xd, 0x6a6c95, 0x1, 0xc00006e2a0)
        /home/nd33p/go/src/github.com/sandeeprenjith/dnsblast/qry/qry.go:31 +0x22e
main.main()
        /home/nd33p/go/src/github.com/sandeeprenjith/dnsblast/main.go:48 +0x2c5

**Comment by sandeeprenjith** [comment]
$ dnsblast
  -len int
        Duration to run load (default 60)
  -port string
        The destination UDP port (default "53")
  -rate int
        Packets per second to send (default 100)
  -server string
        The address of the target server (default "invalid")

**Comment by sandeeprenjith** [comment]
Fixed with 1cf7dbfe838310ce0acab1ae83579c7e1ce0b26f
